spring:
  application:
    name: ds-ai-service
  ai:
    openai:
      api-key: sk-84fc818755b9467ea6a7d5792ca84ba6
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-chat
          temperature: 0.7

