spring:
  application:
    name: tiger-service-ai

  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: deepseek-r1:7b
  data:
    redis:
      port: 6379
      host: localhost

logging:
  level:
    org.springframework.ai.chat.client.advisor: debug
    com.tiger.ai: debug
    com.tiger.ai.com.tiger.ai.configuration: debug


